site_name: IUS Project
repo_url: https://github.com/iuscommunity
strict: True
markdown_extensions:
  - toc:
      permalink: True
pages:
  - index.md
  - Usage:
    - GettingStarted.md
    - Packages.md
  - More Information:
    - Contributing.md
    - History.md
