site_name: IUS
copyright: Sponsered by <a href="https://www.rackspace.com">Rackspace</a>.
strict: True
markdown_extensions:
  - toc:
      permalink: True
pages:
  - index.md
  - About:
    - Philosophy: Philosophy.md
    - History: History.md
    - Packages: Packages.md
    - SafeRepo: SafeRepo.md
  - Usage:
    - Getting Started: GettingStarted.md
    - Usage Guide: UsageGuide.md
  - More Information:
    - Contributing: Contributing.md
    - Life Cycle: LifeCycle.md
    - Software Collections: IUSvsSCL.md
    - FAQs: FAQs.md
