site_name: IUS Project
repo_url: https://github.com/iuscommunity
strict: True
markdown_extensions:
  - toc:
      permalink: True
pages:
  - index.md
  - About:
    - Philosophy: Philosophy.md
    - History: History.md
    - Packages: Packages.md
    - SafeRepo: SafeRepo.md
  - Usage:
    - Getting Started: GettingStarted.md
    - Usage Guide: UsageGuide.md
  - More Information:
    - Contributing: Contributing.md
    - EOL: EOL.md
