site_name: IUS
strict: True
include_next_prev: False
theme: mkdocs
theme_dir: theme
repo_url: https://github.com/iuscommunity-pkg/
markdown_extensions:
  - toc:
      permalink: True
pages:
  - index.md
  - 'About':
    - 'Philosophy': Philosophy.md
    - 'History': History.md
    - 'Packages': Packages.md
  - 'Guides':
    - 'Getting Started': GettingStarted.md
    - 'Usage': Usage.md
  - 'More Information':
    - 'Contributing': Contributing.md
    - 'Mirrors': Mirrors.md
    - 'Life Cycle': LifeCycle.md
    - 'Software Collections': IUSvsSCL.md
    - 'SafeRepo': SafeRepo.md
    - 'Testimonials': Testimonials.md
    - 'FAQs': FAQs.md
